In [15]:
import pandas as pd 
import numpy as np

In [16]:

dataset = pd.read_csv("Salary_Data.csv")

In [18]:

dataset.shape

(6704, 6)

In [19]:

dataset.head(10)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
5,29.0,Male,Bachelor's,Marketing Analyst,2.0,55000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
7,31.0,Male,Bachelor's,Sales Manager,4.0,80000.0
8,26.0,Female,Bachelor's,Marketing Coordinator,1.0,45000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0

In [20]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(3), object(3)
memory usage: 235.8+ KB

In [22]:

dataset.isna()

        Age  Gender  Education Level  Job Title  Years of Experience  Salary
0     False   False            False      False                False   False
1     False   False            False      False                False   False
2     False   False            False      False                False   False
3     False   False            False      False                False   False
4     False   False            False      False                False   False
...     ...     ...              ...        ...                  ...     ...
6699  False   False            False      False                False   False
6700  False   False            False      False                False   False
6701  False   False            False      False                False   False
6702  False   False            False      False                False   False
6703  False   False            False      False                False   False

[6704 rows x 6 columns]

In [23]:
dataset.duplicated().sum()

4912

In [24]:

dataset.drop_duplicates(keep ="first", inplace= True)

In [25]:
dataset.duplicated().sum()

0

In [26]:
dataset.shape

(1792, 6)

In [27]:
dataset.isna().sum()

Age                    1
Gender                 1
Education Level        2
Job Title              1
Years of Experience    2
Salary                 4
dtype: int64

In [28]:
dataset['Age'].unique()

array([32., 28., 45., 36., 52., 29., 42., 31., 26., 38., 48., 35., 40.,
       27., 44., 33., 39., 25., 51., 34., 47., 30., 41., 37., 24., 43.,
       50., 46., 49., 23., 53., nan, 61., 57., 62., 55., 56., 54., 60.,
       58., 22., 21.])

In [29]:

Occupation_mode = dataset.Age.mode()[0]
print(Occupation_mode)

29.0

In [30]:
dataset.Age.fillna(Occupation_mode, inplace=True)

In [31]:
Salary_mode = dataset.Salary.mode()[0]
print(Salary_mode)

120000.0

In [32]:
dataset.Salary.fillna(Salary_mode, inplace=True)

In [33]:
dataset['Salary'].unique()

array([ 90000.,  65000., 150000.,  60000., 200000.,  55000., 120000.,
        80000.,  45000., 110000.,  75000., 140000., 130000.,  40000.,
       125000., 115000.,  35000., 180000., 190000.,  50000., 250000.,
       170000., 160000.,  85000.,  95000., 105000.,  70000., 100000.,
        30000., 135000., 220000., 175000., 185000., 145000., 155000.,
          350., 195000., 198000., 196000., 193000.,  92000., 165000.,
       162000., 197000., 142000., 182000., 210000.,    550., 122485.,
       169159., 187081., 166109.,  78354.,  90249., 132720., 161568.,
       127346., 120177.,  69032., 101332., 121450., 166375., 185119.,
       149217., 166512., 186963.,  75072., 163398., 103947., 179180.,
       175966., 190004., 152039.,  76742., 191790., 139398.,  95845.,
       160976., 126753., 161393., 139817., 181714., 114776., 105725.,
        52731., 106492.,  73895., 119836.,  99747., 168287., 115920.,
       128078.,  51265., 165919., 188651.,  55538., 193964., 104702.,
       172955., 138032.,  82683., 155414., 154207., 107895., 148446.,
       102859., 138662., 181699., 188232.,  51832., 188484., 138286.,
       181132.,  73938., 119224., 101186., 142360., 151315., 181021.,
       134641., 173851., 104127., 178859.,  98568., 104661., 134858.,
        94502.,  62852., 139095., 106278.,  90452., 168304., 126593.,
       152203., 183138., 130275., 191915.,  62807., 174305., 133326.,
        75656., 155944., 137775.,  51831., 182237., 151901., 100052.,
       158254., 167207., 112439., 194214.,  84407., 139413., 143084.,
       192344., 106132., 184816., 150248., 170995.,  88035., 119419.,
       173582., 174436.,  71699., 163558., 166828., 144496., 193746.,
       122581.,  79767., 177177.,  89843., 113563., 128712., 161621.,
       121454., 179987.,  72649.,  52612., 184006., 131960., 102465.,
       149748., 171036., 146351., 185462., 107718.,  90944., 100425.,
        63901., 181902., 136533., 136285., 191818., 176643.,  70022.,
        99363., 152944., 123386., 168906., 183020.,  47898., 135853.,
       149198., 106662., 186610.,  89995.,  85825., 143814., 174726.,
       150534.,  68732., 187951., 137336., 191159., 102868., 154281.,
       111535., 107906., 143885., 180958., 108607., 178284.,  75969.,
       143705., 197354., 174324., 123781., 141735., 187120.,  61095.,
       179045., 130355., 103282., 157872., 117314., 186321., 129686.,
        68611., 177913.,  68472., 113065., 125091., 172925., 126916.,
       183417.,  76898.,    579., 103579., 163780., 137878.,  92438.,
        84181., 174821., 126520., 152168., 190543., 131547., 192292.,
        52807., 174938., 124071.,  73640., 156486., 138859.,  52831.,
       182392., 151078., 100679., 158966., 167924., 113334., 194778.,
        77606., 140010., 142421., 192756., 106686., 186794., 150729.,
       171652.,  88552., 119918., 174985., 174336.,  72389., 163978.,
       166958., 145052., 195270., 122970.,  80247., 177862.,  91062.,
       114290., 128999., 162454., 122354., 179756.,  73218., 184480.,
       132442., 102828., 150301., 171468., 147326., 185982., 108267.,
        91397., 100867.,  64182., 182506., 136986., 136662., 191510.,
       177347.,  70397., 146075., 155795., 132638., 178684., 106218.,
       191239.,  65840.,  52779., 185038., 136449., 110707., 151670.,
       167015., 146508., 190596., 104378.,  70216., 101733.,  55935.,
       180367., 135596., 136062., 191267.,  82944., 188288., 141090.,
       152726., 124141.,  67556., 182768., 148727.,  91903., 147708.,
       163209., 120288., 170226., 134979., 137489.,  83577., 117904.,
       134482., 184660., 100151.,  88678., 181285., 154990., 108204.,
       175684.,  77766., 192211., 144647., 162231., 121120.,  79652.,
       177002.,  87584., 131860., 182013., 108799., 135378., 183530.,
       150901.,  82697., 194638., 130356., 152560., 121432.,  63789.,
       183690., 151310., 100358., 148437., 168691.,  32000.,  38000.,
        89000.,  33000.,  25000.,  62000., 138000.,  47000.,  26000.,
       174000.,  41000.,  99000., 117000., 225000.,  36000., 146000.,
       113000., 168000., 122000.,  96000.,  49000.,  68000., 127000.,
        71000., 240000., 152000., 119000., 131000., 101000., 137000.,
       112000.,  91000., 179000.,  74000., 228000.,  37000., 204000.,
        61000., 157000.,  52000.,  58000., 219000.,  77000., 104000.,
       183000.,  43000.,  48000.,  42000.,    500.,  57000.,  72000.,
        31000.,  28000., 215000.])

In [50]:
dataset['Salary'] = dataset['Salary'].astype(str).str.replace("k", "000")

In [51]:
dataset['Salary'] = dataset['Salary'].astype(str).str.replace("usd","")

In [52]:
dataset['Salary'] = dataset['Salary'].astype(str).str.replace("USD","")

In [53]:
dataset['Salary'] = dataset['Salary'].replace("USD","")

In [54]:
dataset['Salary'] = dataset['Salary'].replace("$","")

In [55]:
dataset['Salary'].unique()

array(['90000.0', '65000.0', '150000.0', '60000.0', '200000.0', '55000.0',
       '120000.0', '80000.0', '45000.0', '110000.0', '75000.0',
       '140000.0', '130000.0', '40000.0', '125000.0', '115000.0',
       '35000.0', '180000.0', '190000.0', '50000.0', '250000.0',
       '170000.0', '160000.0', '85000.0', '95000.0', '105000.0',
       '70000.0', '100000.0', '30000.0', '135000.0', '220000.0',
       '175000.0', '185000.0', '145000.0', '155000.0', '350.0',
       '195000.0', '198000.0', '196000.0', '193000.0', '92000.0',
       '165000.0', '162000.0', '197000.0', '142000.0', '182000.0',
       '210000.0', '550.0', '122485.0', '169159.0', '187081.0',
       '166109.0', '78354.0', '90249.0', '132720.0', '161568.0',
       '127346.0', '120177.0', '69032.0', '101332.0', '121450.0',
       '166375.0', '185119.0', '149217.0', '166512.0', '186963.0',
       '75072.0', '163398.0', '103947.0', '179180.0', '175966.0',
       '190004.0', '152039.0', '76742.0', '191790.0', '139398.0',
       '95845.0', '160976.0', '126753.0', '161393.0', '139817.0',
       '181714.0', '114776.0', '105725.0', '52731.0', '106492.0',
       '73895.0', '119836.0', '99747.0', '168287.0', '115920.0',
       '128078.0', '51265.0', '165919.0', '188651.0', '55538.0',
       '193964.0', '104702.0', '172955.0', '138032.0', '82683.0',
       '155414.0', '154207.0', '107895.0', '148446.0', '102859.0',
       '138662.0', '181699.0', '188232.0', '51832.0', '188484.0',
       '138286.0', '181132.0', '73938.0', '119224.0', '101186.0',
       '142360.0', '151315.0', '181021.0', '134641.0', '173851.0',
       '104127.0', '178859.0', '98568.0', '104661.0', '134858.0',
       '94502.0', '62852.0', '139095.0', '106278.0', '90452.0',
       '168304.0', '126593.0', '152203.0', '183138.0', '130275.0',
       '191915.0', '62807.0', '174305.0', '133326.0', '75656.0',
       '155944.0', '137775.0', '51831.0', '182237.0', '151901.0',
       '100052.0', '158254.0', '167207.0', '112439.0', '194214.0',
       '84407.0', '139413.0', '143084.0', '192344.0', '106132.0',
       '184816.0', '150248.0', '170995.0', '88035.0', '119419.0',
       '173582.0', '174436.0', '71699.0', '163558.0', '166828.0',
       '144496.0', '193746.0', '122581.0', '79767.0', '177177.0',
       '89843.0', '113563.0', '128712.0', '161621.0', '121454.0',
       '179987.0', '72649.0', '52612.0', '184006.0', '131960.0',
       '102465.0', '149748.0', '171036.0', '146351.0', '185462.0',
       '107718.0', '90944.0', '100425.0', '63901.0', '181902.0',
       '136533.0', '136285.0', '191818.0', '176643.0', '70022.0',
       '99363.0', '152944.0', '123386.0', '168906.0', '183020.0',
       '47898.0', '135853.0', '149198.0', '106662.0', '186610.0',
       '89995.0', '85825.0', '143814.0', '174726.0', '150534.0',
       '68732.0', '187951.0', '137336.0', '191159.0', '102868.0',
       '154281.0', '111535.0', '107906.0', '143885.0', '180958.0',
       '108607.0', '178284.0', '75969.0', '143705.0', '197354.0',
       '174324.0', '123781.0', '141735.0', '187120.0', '61095.0',
       '179045.0', '130355.0', '103282.0', '157872.0', '117314.0',
       '186321.0', '129686.0', '68611.0', '177913.0', '68472.0',
       '113065.0', '125091.0', '172925.0', '126916.0', '183417.0',
       '76898.0', '579.0', '103579.0', '163780.0', '137878.0', '92438.0',
       '84181.0', '174821.0', '126520.0', '152168.0', '190543.0',
       '131547.0', '192292.0', '52807.0', '174938.0', '124071.0',
       '73640.0', '156486.0', '138859.0', '52831.0', '182392.0',
       '151078.0', '100679.0', '158966.0', '167924.0', '113334.0',
       '194778.0', '77606.0', '140010.0', '142421.0', '192756.0',
       '106686.0', '186794.0', '150729.0', '171652.0', '88552.0',
       '119918.0', '174985.0', '174336.0', '72389.0', '163978.0',
       '166958.0', '145052.0', '195270.0', '122970.0', '80247.0',
       '177862.0', '91062.0', '114290.0', '128999.0', '162454.0',
       '122354.0', '179756.0', '73218.0', '184480.0', '132442.0',
       '102828.0', '150301.0', '171468.0', '147326.0', '185982.0',
       '108267.0', '91397.0', '100867.0', '64182.0', '182506.0',
       '136986.0', '136662.0', '191510.0', '177347.0', '70397.0',
       '146075.0', '155795.0', '132638.0', '178684.0', '106218.0',
       '191239.0', '65840.0', '52779.0', '185038.0', '136449.0',
       '110707.0', '151670.0', '167015.0', '146508.0', '190596.0',
       '104378.0', '70216.0', '101733.0', '55935.0', '180367.0',
       '135596.0', '136062.0', '191267.0', '82944.0', '188288.0',
       '141090.0', '152726.0', '124141.0', '67556.0', '182768.0',
       '148727.0', '91903.0', '147708.0', '163209.0', '120288.0',
       '170226.0', '134979.0', '137489.0', '83577.0', '117904.0',
       '134482.0', '184660.0', '100151.0', '88678.0', '181285.0',
       '154990.0', '108204.0', '175684.0', '77766.0', '192211.0',
       '144647.0', '162231.0', '121120.0', '79652.0', '177002.0',
       '87584.0', '131860.0', '182013.0', '108799.0', '135378.0',
       '183530.0', '150901.0', '82697.0', '194638.0', '130356.0',
       '152560.0', '121432.0', '63789.0', '183690.0', '151310.0',
       '100358.0', '148437.0', '168691.0', '32000.0', '38000.0',
       '89000.0', '33000.0', '25000.0', '62000.0', '138000.0', '47000.0',
       '26000.0', '174000.0', '41000.0', '99000.0', '117000.0',
       '225000.0', '36000.0', '146000.0', '113000.0', '168000.0',
       '122000.0', '96000.0', '49000.0', '68000.0', '127000.0', '71000.0',
       '240000.0', '152000.0', '119000.0', '131000.0', '101000.0',
       '137000.0', '112000.0', '91000.0', '179000.0', '74000.0',
       '228000.0', '37000.0', '204000.0', '61000.0', '157000.0',
       '52000.0', '58000.0', '219000.0', '77000.0', '104000.0',
       '183000.0', '43000.0', '48000.0', '42000.0', '500.0', '57000.0',
       '72000.0', '31000.0', '28000.0', '215000.0'], dtype=object)

In [61]:
YearsOfExperience_median = dataset['Years of Experience'].median()
print(YearsOfExperience_median)

8.0

In [62]:
dataset['Years of Experience'].fillna(dataset['Years of Experience'].median(), inplace=True)

In [63]:
dataset['Years of Experience'].fillna(dataset['Years of Experience'].median(), inplace=True)

In [64]:
dataset['Years of Experience'].unique()

array([ 5. ,  3. , 15. ,  7. , 20. ,  2. , 12. ,  4. ,  1. , 10. , 18. ,
        6. , 14. , 16. ,  0. , 22. , 19. ,  9. , 13. , 11. , 25. , 21. ,
        8. , 17. , 23. , 24. ,  0.5,  1.5, 31. , 30. , 28. , 33. , 27. ,
       34. , 29. , 26. , 32. ])

In [65]:
YearsOfExperience_mode = dataset['Years of Experience'].mode()[0]
print(YearsOfExperience_mode)

2.0

In [66]:
dataset['Years of Experience'].fillna(dataset['Years of Experience'].mode()[0], inplace=True)

In [70]:
dataset['Years of Experience'].unique()

array(['5.0', '3.0', '15.0', '7.0', '20.0', '2.0', '12.0', '4.0', '1.0',
       '10.0', '18.0', '6.0', '14.0', '16.0', '0.0', '22.0', '19.0',
       '9.0', '13.0', '11.0', '25.0', '21.0', '8.0', '17.0', '23.0',
       '24.0', '0.5', '1.5', '31.0', '30.0', '28.0', '33.0', '27.0',
       '34.0', '29.0', '26.0', '32.0'], dtype=object)

In [69]:
dataset['Years of Experience'] = dataset['Years of Experience'].astype(str).str.replace("ears", "")

In [71]:
dataset['Years of Experience'].unique()

array(['5.0', '3.0', '15.0', '7.0', '20.0', '2.0', '12.0', '4.0', '1.0',
       '10.0', '18.0', '6.0', '14.0', '16.0', '0.0', '22.0', '19.0',
       '9.0', '13.0', '11.0', '25.0', '21.0', '8.0', '17.0', '23.0',
       '24.0', '0.5', '1.5', '31.0', '30.0', '28.0', '33.0', '27.0',
       '34.0', '29.0', '26.0', '32.0'], dtype=object)

In [73]:
dataset['Years of Experience'] = dataset['Years of Experience'].astype(str).str.replace("ears", "")

In [74]:
dataset['Years of Experience'].unique()

array(['5.0', '3.0', '15.0', '7.0', '20.0', '2.0', '12.0', '4.0', '1.0',
       '10.0', '18.0', '6.0', '14.0', '16.0', '0.0', '22.0', '19.0',
       '9.0', '13.0', '11.0', '25.0', '21.0', '8.0', '17.0', '23.0',
       '24.0', '0.5', '1.5', '31.0', '30.0', '28.0', '33.0', '27.0',
       '34.0', '29.0', '26.0', '32.0'], dtype=object)

In [76]:
dataset['Years of Experience'] = dataset['Years of Experience'].str.replace("y", "")

In [77]:
dataset['Years of Experience'].unique()

array(['5.0', '3.0', '15.0', '7.0', '20.0', '2.0', '12.0', '4.0', '1.0',
       '10.0', '18.0', '6.0', '14.0', '16.0', '0.0', '22.0', '19.0',
       '9.0', '13.0', '11.0', '25.0', '21.0', '8.0', '17.0', '23.0',
       '24.0', '0.5', '1.5', '31.0', '30.0', '28.0', '33.0', '27.0',
       '34.0', '29.0', '26.0', '32.0'], dtype=object)

In [78]:
dataset.isna().sum()

Age                    0
Gender                 1
Education Level        2
Job Title              1
Years of Experience    0
Salary                 0
dtype: int64

In [79]:
dataset['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', nan, "Bachelor's Degree",
       "Master's Degree", 'High School', 'phD'], dtype=object)

In [80]:
FinanceStatus_mode = dataset['Education Level'].mode()[0]
print(FinanceStatus_mode)

Bachelor's Degree

In [81]:
dataset['Education Level'].fillna(FinanceStatus_mode, inplace=True)

In [82]:
dataset['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', "Bachelor's Degree",
       "Master's Degree", 'High School', 'phD'], dtype=object)